application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['namespace' => 'Admin', 'prefix' => 'administration', 'as'=>'admin.'], function () {

    Auth::routes();

    Route::group(['middleware' => 'auth:admin'], function () {

        Route::get('/', 'IndexController@index')->name('index.index');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

        Route::resource('admins', 'AdminsController');
        Route::put('/admins/update_password/{id}', 'AdminsController@update_password')->name('admins.update_password');

    });
});


Auth::routes();
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.provider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('login.callback_provider');


Route::group(['middleware' => 'auth:web'], function () {
    Route::view('/', 'index');
});

Route::get('/test', 'DashboardController@testBackofficeConnection');
Route::get('/{index?}', 'DashboardController@index');


Route::get('/algorithme', 'DashboardController@algorithme');

application/resources/views/admin/layouts/partials/footer.blade.php
<footer class="main-footer">
  <strong>Copyright &copy; 2017 <a href="">Mes Voyages</a>.</strong> Made With <i style="color: red;" class="fa fa-heart"></i> In France
</footer>

application/resources/views/admin/layouts/partials/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ asset('admin/css/app.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @stack('css')
</head>

application/resources/views/admin/layouts/partials/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="{{ url('/') }}" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>TDB</b>DEV</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>TdB Dev</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
	    @yield('header')
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ !is_null($admin)?$admin->avatar:'' }}" class="user-image" alt="User Image">
            <span class="hidden-xs">logged : {{ !is_null($admin)?$admin->name:'' }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="{{ !is_null($admin)?$admin->avatar:'' }}" class="img-circle" alt="User Image">

              <p>
                {{ $admin->name }}
                <small>Membre depuis le {{$admin->created_at->format('d/m/Y')}}</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ route('admin.admins.edit', ['id' => $admin->id]) }}" class="btn btn-default btn-flat">Profil</a>
              </div>
              <div class="pull-right">
                <form action="{{ route('admin.logout') }}" method="POST">
                  <input type="submit" class="btn btn-default btn-flat" value="D&eacute;connexion"/>
                </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

application/resources/views/admin/layouts/partials/sidebar.blade.php
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li {!! ViewHelper::isActiveRoute('/', 'class="active"') !!}>
        <a href="{{ route('admin.dashboard.index') }}">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>
      <li {!! ViewHelper::isActiveRoute('admin.administrateurs.*', 'class="active"') !!}>
        <a href="{{ route('admin.admins.index') }}">
          <i class="fa fa-pie-chart"></i> <span>Administrateurs</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>