application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['namespace' => 'Admin', 'prefix' => 'administration', 'as'=>'admin.'], function () {

    Auth::routes();

    Route::group(['middleware' => 'auth:admin'], function () {

        Route::get('/', 'IndexController@index')->name('index.index');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

        Route::resource('admins', 'AdminsController');
        Route::put('/admins/update_password/{id}', 'AdminsController@update_password')->name('admins.update_password');

    });
});


Auth::routes();
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('login.provider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('login.callback_provider');


Route::group(['middleware' => 'auth:web'], function () {
    Route::view('/', 'index');
});

Route::get('/test', 'DashboardController@testBackofficeConnection');
Route::get('/{index?}', 'DashboardController@index');


Route::get('/algorithme', 'DashboardController@algorithme');

application/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 'name', 'email', 'password', 'birthdate', 'street1', 'street2', 'postal_code', 'city', 'region_id',
        'user_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function getFullnameAttribute()
    {
        return $this->firstname.' '. $this->name;
    }

    public function users()
    {
        return $this->hasMany('App\Models\User');
    }


    public function scopeOfAdmin($query, $admin)
    {
        if($admin->region_id !=0) {
            return $query->where('region_id', $admin->region_id);
        } else {
            return $query;
        }
    }
}

application/resources/views/admin/users/_change_interests.blade.php
{{ Form::open(array('url' => $url, 'method' => $method, 'files' => true)) }}
<div class="box-body">
    @if (count($errors->changeInterests) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->changeInterests->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @foreach($competition_types as $type)
        {!! FormHelper::formGroupCheckbox('types[]',$type->title, $user->competitionTypes->contains($type->id), $type->id, $type->id, true) !!}
    @endforeach

</div>
<!-- /.box-body -->

<div class="box-footer">
    <button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
{{ Form::close() }}

application/resources/views/admin/users/_change_password.blade.php
{{ Form::open(array('url' => $url, 'method' => $method, 'files' => true)) }}
<div class="box-body">
    @if (count($errors->changePassword) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->changePassword->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Saisir le nouveau mot de passe" value="">
    </div>

    <div class="form-group">
        <label for="password_confirmation">Mot de passe </label>
        <input type="password" class="form-control" id="password_confirmation" name="password_confirmation" placeholder="Saisir à nouveau le mot de passe " value="">
    </div>
</div>
<!-- /.box-body -->

<div class="box-footer">
    <button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
{{ Form::close() }}

application/resources/views/admin/users/_form.blade.php
{{ Form::open(array('url' => $url, 'method' => $method, 'files' => true)) }}
<div class="box-body">
    @if (count($errors->storeAdmin) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->storeAdmin->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

        {!! FormHelper::formGroupInput('firstname', 'Prénom', $user->firstname, 'text', 'Prénom') !!}
        {!! FormHelper::formGroupInput('name', 'Nom', $user->name, 'text', 'Le Nom') !!}
        {!! FormHelper::formGroupInput('email', 'Email', $user->email, 'email', 'Le mail') !!}
        {!! FormHelper::formGroupInput('birthdate', 'Date de Naissance', $user->birthdate, 'date', '') !!}
        {!! FormHelper::formGroupInput('street1', 'Adresse', $user->street1, 'text', 'Adresse') !!}
        {!! FormHelper::formGroupInput('street2', 'Complément d\'adresse', $user->street2, 'text', 'Complément') !!}
        {!! FormHelper::formGroupInput('postal_code', 'Code Postal', $user->postal_code, 'text', 'Code Postal') !!}
        {!! FormHelper::formGroupInput('city', 'Ville', $user->city, 'text', 'Ville') !!}
        {!! FormHelper::formGroupSelect('region_id', 'Région', $user->region_id, $regions) !!}
        {!! FormHelper::formGroupInput('user_id', 'Associé à', $user_id, 'text', '') !!}

</div>
<!-- /.box-body -->

<div class="box-footer">
    <button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
{{ Form::close() }}

application/resources/views/admin/users/accounts.blade.php
@extends('admin.layouts.app')

@section('title', 'Liste des comptes associés')
@section('subtitle', '')


@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Les comptes associés à {{ $user->fullname }}</h3>
                    <a href="{{route('admin.users.create', ['user_id' => $user->id])}}" class="pull-right btn btn-success"><i class="fa fa-plus"></i></a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th>email</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Région</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->email}}</td>
                                <td>{{$user->firstname}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->region->title}}</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default">Action</button>
                                        <button type="button" class="btn btn-default dropdown-toggle"
                                                data-toggle="dropdown" aria-expanded="false">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="{{route('admin.users.edit', ['id' => $user->id])}}"><i
                                                            class="fa fa-edit"></i>Modifier</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="javascript:void(0);" onclick="$(this).find('form').submit();">
                                                    {{ Form::open(array('url' => route('admin.users.destroy', ['id' => $user->id]))) }}
                                                    {{ Form::hidden('_method', 'DELETE') }}
                                                    {{ Form::close() }}
                                                    <i class="fa fa-trash-o"></i>Supprimer
                                                </a>
                                            </li>
                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    <!-- /.col -->
    </div>


@endsection

application/resources/views/admin/users/achats.blade.php
@extends('admin.layouts.app')

@section('title', 'Liste des Achats de ')
@section('subtitle', '')


@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Les Adhérents</h3>
                    <a href="{{route('admin.users.create')}}" class="pull-right btn btn-success"><i class="fa fa-plus"></i></a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th>email</th>
                            <th>Nom</th>
                            <th>Région</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->email}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->region->title}}</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default">Action</button>
                                        <button type="button" class="btn btn-default dropdown-toggle"
                                                data-toggle="dropdown" aria-expanded="false">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="{{route('admin.users.edit', ['id' => $user->id])}}"><i
                                                            class="fa fa-edit"></i>Modifier</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{{route('admin.users.achats', ['id' => $user->id])}}"><i
                                                            class="fa fa-credit-card"></i>Voir ses achats</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="javascript:void(0);" onclick="$(this).find('form').submit();">
                                                    {{ Form::open(array('url' => route('admin.users.destroy', ['id' => $user->id]))) }}
                                                    {{ Form::hidden('_method', 'DELETE') }}
                                                    {{ Form::close() }}
                                                    <i class="fa fa-trash-o"></i>Supprimer
                                                </a>
                                            </li>
                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    <!-- /.col -->
    </div>


@endsection

application/resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Ajouter un nouvel adhérent')
@section('subtitle', 'V1.0')


@section('content')

	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
			@include('admin.users._form', ['url' => route('admin.users.store'), 'method' => 'POST'])
			</div>
		</div>
	</div>
@endsection

application/resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Edition du profil adhérent')
@section('subtitle', 'V1.0')

@section('content')

	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Informations générales</h3>
				</div>
				@include('admin.users._form', ['url' => route('admin.users.update', ['id' => $user->id]), 'method' => 'PUT'])

			</div>
		</div>

		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Changer de mot de passe</h3>
				</div>
				@include('admin.users._change_password', ['url' => route('admin.users.update_password', ['id' => $user->id]), 'method' => 'PUT'])

			</div>
		</div>

		<div class="col-md-6">
			<div class="box box-primary">
				<div class="box-header with-border">
					<h3 class="box-title">Intéressé par</h3>
				</div>
				@include('admin.users._change_interests', ['url' => route('admin.users.update_interests', ['id' => $user->id]), 'method' => 'PUT'])

			</div>
		</div>
	</div>

@endsection

application/resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Liste des Adhérents')
@section('subtitle', '')


@section('content')


    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>150</h3>

                    <p>New Orders</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>53<sup style="font-size: 20px">%</sup></h3>

                    <p>Bounce Rate</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>44</h3>

                    <p>User Registrations</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>65</h3>

                    <p>Unique Visitors</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Les Adhérents</h3>
                    <a href="{{route('admin.users.create')}}" class="pull-right btn btn-success"><i class="fa fa-plus"></i></a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody>
                        <tr>
                            <th>email</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Région</th>
                            <th>Actions</th>
                        </tr>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->email}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->firstname}}</td>
                                <td>{{$user->region->title}}</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default">Action</button>
                                        <button type="button" class="btn btn-default dropdown-toggle"
                                                data-toggle="dropdown" aria-expanded="false">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="{{route('admin.users.edit', ['id' => $user->id])}}"><i
                                                            class="fa fa-edit"></i>Modifier</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{{route('admin.users.achats', ['id' => $user->id])}}"><i
                                                            class="fa fa-credit-card"></i>Voir ses achats</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{{route('admin.users.accounts', ['id' => $user->id])}}"><i
                                                            class="fa fa-users"></i>Voir les comptes associés</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="javascript:void(0);" onclick="$(this).find('form').submit();">
                                                    {{ Form::open(array('url' => route('admin.users.destroy', ['id' => $user->id]))) }}
                                                    {{ Form::hidden('_method', 'DELETE') }}
                                                    {{ Form::close() }}
                                                    <i class="fa fa-trash-o"></i>Supprimer
                                                </a>
                                            </li>
                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    <!-- /.col -->
    </div>


@endsection

application/resources/views/admin/users/show.blade.php
@extends('admin.layouts.app')

@section('title', 'Tableau de bord des développements informatique')
@section('subtitle', 'V1.0')

@section('content')
	<div class="row">
		<div class="col-md-6">
			<div class="box box-primary">

			</div>
		</div>
	</div>
@endsection